services:
    firebase-emulator:
        image: andreysenov/firebase-tools:13.8.2-node-18
        container_name: firebase-emulator
        working_dir: /workspace
        volumes:
            - .:/workspace
        ports:
            - '4000:4000'
            - '9000:9000'
            - '9099:9099'
            - '8090:8080'
            - '9199:9199'
            - '5001:5001'
        command: firebase emulators:start --project=demo-uni-event --only auth,firestore,database,storage,functions

    expo-web:
        image: node:18
        container_name: expo-web
        working_dir: /workspace/app
        volumes:
            - .:/workspace
            - node_modules_cache:/workspace/app/node_modules
        env_file:
            - ./app/.env
        ports:
            - '8081:8081'
        environment:
            - EXPO_PUBLIC_USE_EMULATORS=true
            - EXPO_NO_TELEMETRY=1
            - NPM_CONFIG_LOGLEVEL=error
            - CI=1
        command: sh -c "npm install && npx expo export --platform web  && echo 'Build done' && npx serve dist -p 8081 --no-clipboard"
        depends_on:
            - firebase-emulator

volumes:
    node_modules_cache:
